- field_friend/hardware/flashlight_pwm.py
This PR implements a hardware-near calculation of the `duty_cycle` for the `FlashlightPwm` module.
> rewrite duty cycle calculation

- field_friend/automations/automation_watcher.py
- field_friend/automations/plant_locator.py
- field_friend/interface/components/monitoring.py
- field_friend/interface/components/robot_scene.py
- field_friend/interface/pages/monitor_page.py
- field_friend/system.py
- field_friend/vision/camera_configurator.py
- main.py
This pull request contains some general formatting and type changes which I encountered while reviewing the code.
> General code review

- field_friend/automations/plant_locator.py
- field_friend/automations/weeding.py
- field_friend/interface/components/operation.py
- field_friend/system.py
This PR fixes the backing up of the weeding automation. By using the persistence_key to distinguish between weeding and monitoring.
> implement persistence_key to distinguish between weeding automation

- field_friend/automations/plant_locator.py
- field_friend/automations/plant_provider.py
- field_friend/automations/weeding.py
Add a list of the last seen positions ( to a max of 20) to the Plant class.
> Plants with position list

- field_friend/interface/components/leaflet_map.py
- field_friend/interface/components/operation.py
This PR improves the UI by making the "zoom to field" button part of the leaflet_map.
> Put "zoom to field" into the map's button bar

- field_friend/automations/field_provider.py
- field_friend/interface/components/operation.py
This PR fixes and improves the persistence of field selection. It also simplifies the code a bit due to the use of data bindings.
> Fix, improve and simplify field selection

- pytest.ini
- tests/conftest.py
- tests/test_gnss.py
This pull request is based on the RoSys improved pytest support from https://github.com/zauberzeug/rosys/pull/111 and shows how to write powerful integration tests.
> Introduce pytest infrastructure and demonstrate usage with simple gnss test

- field_friend/hardware/__init__.py
- field_friend/hardware/can_open_master.py
- field_friend/hardware/field_friend_hardware.py
- field_friend/hardware/y_axis_canopen_hardware.py
This PR implements the CanOpenMaster module als a seperate hardware module, which is created if one of the axis ist a CanOpenMotorAxis.
> Can open master

- field_friend/automations/plant_provider.py
- field_friend/automations/weeding.py
- field_friend/interface/components/punch_dialog.py
Calculate sum of all detection confidences and predict plant position from known plant row
> Make plant positioning more robust

- field_friend/interface/components/header_bar.py
- field_friend/interface/components/status_dev.py
- field_friend/system.py
This pull request shows the user which estops are pressed at the moment and improves the naming of the battery output connector status.
> Improve status output for problem analysis

- field_friend/system.py
Thymian is already a category in the Learning Loop.
> Add thymian as category

- sync.py
With this change the local RoSys code is no longer copied onto the robot while using LiveSync. This will get us more stability in trade of flexibility. [Link to Rosys 0.10.10](https://github.com/zauberzeug/rosys/releases/tag/v0.10.10)
For each robot we have synced before we must:
1. remove the  `~/field_friend/rosys` directory
2. rebuild the container with `cd ~/field_friend/; ./docker.sh U rosys`
**ToDos**
> Stick to latest RoSys release (0.10.10)

- field_friend/automations/plant_provider.py
When settings are changed for the plant_provider, it now requests a persistence backup.
> Request backup on settings change for plant_provider

- docker-compose.jetson.orin.yml
> Update detector to 0.1.1-nlv0.10.9-35.4.1

- field_friend/system.py
This PR adds battery infos to the status log which runs every 5 min.
> Log battery infos

- config/u3_config_rb27/hardware.py
- field_friend/system.py
This PR tracks the changes necessary to get U3 running again. It's still work in progress.
**ToDos**
> Reactivate U3

- config/ff12_config_rb32/params.py
> change work x of the ff12

- requirements.txt
- sync.py
This PR updates RoSys. And it improves the sync.py to ensure we do not have a local rosys dir if we do not want it.
> use RoSys 0.12.0 and improve sync.py

- docker-compose.jetson.orin.yml
This PR uses the latest detector. And makes the docker compose file more readable.
It was already tested successfully on a robot yesterday.
> Use latest detector

- field_friend/automations/implements/tornado.py
- field_friend/automations/puncher.py
- field_friend/hardware/tornado.py
Provide a checkbox to run tornado in demo mode (eg. stop before the ground).
> Punch demo

- config/u4_config_rb28/hardware.py
- field_friend/hardware/field_friend_hardware.py
- field_friend/hardware/tornado.py
- field_friend/interface/components/status_dev.py
Add funktionality to check the tornado Odrive for motor errors.
Update the U4 Odrives to 0.5.6.
> U4 odrive update

- field_friend/interface/components/camera_card.py
As decided [here](https://github.com/zauberzeug/field_friend/pull/152#issuecomment-2312937118) we need to fix the implement overlay of the camera_card, but for now this PR removes it.
> Remove implement svg for now

- field_friend/automations/plant_locator.py
- field_friend/hardware/teltonika_router.py
- field_friend/interface/components/development.py
- field_friend/interface/components/settings.py
I added a switch to activate the image upload via mobile as described in #166.
> Upload Images via Mobile Switch

- field_friend/automations/implements/weeding_implement.py
- field_friend/automations/implements/weeding_screw.py
- field_friend/automations/navigation/follow_crops_navigation.py
- field_friend/automations/plant.py
- field_friend/automations/plant_locator.py
- field_friend/automations/plant_provider.py
- tests/test_navigation.py
- tests/test_plant_provider.py
- tests/test_recorder.py
We need 3d positions for plants for 3d cameras, this PR adds this for all cameras with default z=0
> Make plant positions Point3d

- field_friend/automations/implements/weeding_implement.py
- field_friend/interface/components/field_planner.py
The last PR https://github.com/zauberzeug/field_friend/pull/181 was missing these two changes
> Fix wrong crop_category_names for implements

- tests/test_weeding.py
I was too impatient, when I pushed https://github.com/zauberzeug/field_friend/commit/13b7d6fca26959824ac3bd79b1d3ac550e71101a. So this fixes the failing tests.
Big_weed was removed but some tests still used it.
> Fix weeding tests because big_weed was removed

- field_friend/vision/calibratable_usb_camera_provider.py
- field_friend/vision/zedxmini_camera/zedxmini_camera_provider.py
When starting the fieldfriend the camera will log its whole dict. Now it will lig its name.
> Change log of camera

- field_friend/automations/implements/implement.py
- field_friend/automations/puncher.py
- field_friend/interface/components/status_dev.py
- field_friend/interface/components/status_drawer.py
- field_friend/interface/pages/__init__.py
- main.py
remove references to old kpis and kpi page
> remove kpi

- .github/workflows/test.yml
This speeds up the test workflow and removes unnecessary steps
> Use pip-cache for github tests

- field_friend/hardware/teltonika_router.py
There was a small bug in handling the Teltonika status. Fixed it
> Teltonika Status Fix

- field_friend/automations/automation_watcher.py
- field_friend/automations/navigation/navigation.py
If a running automation is stopped, time recording does not stop. With this PR, I suggest improvements for time recording.
> KPI Time Logging Fix

- field_friend/hardware/teltonika_router.py
As mentioned in issue #204 there is no smooth handling for Teltonika connect errors. I added the httpcore.ConnectError to the exception of trying to connect to the router
> Teltonika Connection Error Handling

- field_friend/automations/navigation/field_navigation.py
- field_friend/automations/navigation/navigation.py
The robot doesn't reach the correct starting position when changing rows during the field navigation, this will help for now.
Will be tested on a robot tomorrow.
> Drive in small steps to next row

- field_friend/automations/navigation/field_navigation.py
This PR introduces:
1. Improve check if robot has reached the end of a row
2. FollowCrops is not stable -> Field Navigation now extends StraightLine
3. Starting from any row
4. Make plant row simulation more realistic
5. Improve developer parameters
> FieldNavigation Improvements

- field_friend/automations/field.py
Hello,
Small fix for the 1 row edge-case for field 1-row _generate_outline.
> Fix edge-case for _generate_outline for field

- field_friend/hardware/z_axis_canopen_hardware.py
This PR fixes the weeding screw until https://github.com/zauberzeug/lizard/issues/66 is fixed. Like https://github.com/zauberzeug/field_friend/pull/213 did it for the tornado.
> Temporary Weeding Screw fix for Lizard issue 66

- field_friend/hardware/y_axis_stepper_hardware.py
- field_friend/hardware/z_axis_canopen_hardware.py
- field_friend/hardware/z_axis_stepper_hardware.py
Still needs to be tested on U4, but for that we need https://github.com/zauberzeug/lizard/issues/99
> Add lizard level fix for U4

- config/f16_config_rb43/camera.py
- config/f16_config_rb43/hardware.py
- config/f16_config_rb43/params.py
- config/f16_config_rb43/robotbrain.py
add the config for the robot f16.
> add config for f16

- config/f18_config_rb47/camera.py
- config/u4_config_rb28/camera.py
- field_friend/interface/components/monitoring.py
On some robots, the circular sight cameras are connected differently. To accommodate this behavior, we want to make the position configurable.
> Make circle sight camera position configurable

- config/ff10XL_config_rb30/hardware.py
- config/ff10XL_config_rb30/params.py
- config/ff10XL_config_rb30/robotbrain.py
while migrating the configs the config for f10 was lost. This is a restoration of the config
> add f10 config

- field_friend/automations/implements/implement.py
- field_friend/automations/implements/weeding_implement.py
- field_friend/automations/navigation/field_navigation.py
- field_friend/automations/navigation/follow_crops_navigation.py
- field_friend/automations/navigation/navigation.py
- field_friend/automations/navigation/straight_line_navigation.py
- field_friend/automations/puncher.py
- field_friend/interface/dev_page.py
This change allows to see the current state of the navigation and of the automation. This is shown as a mermaid diagramm.
> add @track to the automations and navigations

- field_friend/log_configuration.py
The log changes made in https://github.com/zauberzeug/field_friend/pull/253 were a little too verbose.
This PR goes back to the [old configuration](https://github.com/zauberzeug/field_friend/blob/9c4189c9a79456d16520e5e2a9314baeb124e06d/field_friend/log_configuration.py), but implements more logging_queues like [here](https://github.com/zauberzeug/active_cleaner/blob/5308e1041678be0cf4ea940f0bee726fa143e0b0/active_cleaner/log_configuration.py).
> Clean up log configuration

- field_friend/robot_locator.py
- field_friend/vision/camera_configurator.py
Setting the default IMU yaw noise to a value we found fitting after testing.
There was also a type checker error that is fixed now.
> Set IMU default noise

- docker-compose.jetson.orin.yml
This will update the detector to 0.1.10-nlv0.13.4-35.4.1
> Update detector to 0.1.10-nlv0.13.4-35.4.1

- field_friend/automations/__init__.py
- field_friend/automations/entity_locator.py
- field_friend/automations/plant_locator.py
- field_friend/interface/components/operation.py
- field_friend/interface/dev_page.py
This pull request introduces an EntityLocator base class that serves as a foundation for future classes that use sensor data to locate objects in 3d space. The existing PlantLocator has been refactored to inherit from this new base class.
And I moved the ui from the operations block to the dev page
> Add EntityLocator base class

- field_friend/hardware/__init__.py
- field_friend/system.py
To make it easier to overwrite certain parts of the system setup for non-standard robots, I moved these parts to their own submethods.
> Split system setup into sub methods

- field_friend/hardware/field_friend.py
- field_friend/hardware/field_friend_hardware.py
- field_friend/hardware/field_friend_simulation.py
- field_friend/system.py
The old code makes it hard to use an alternative implement in a hardware class that extends `field_friend_hardware`
> Improve hardware setup error handling

- config/u6_config_rb34/params.py
- field_friend/automations/implements/tornado.py
- field_friend/automations/implements/weeding_implement.py
- field_friend/automations/puncher.py
Previously the demo mode was only available for the tornado implement. I also adjusted the `work_x` offset for U6.
> Add demo mode for weeding screw

- field_friend/interface/components/field_creator.py
- field_friend/interface/components/field_friend_object.py
- field_friend/interface/components/monitoring.py
- field_friend/interface/components/operation.py
- field_friend/interface/dev_page.py
Not all robots use the plant locator and the monitoring cameras.
> Check if locators and detectors are available

- requirements-dev.txt
This adds the odrive package to the dev requirements.
> Add odrive to dev requirements

- field_friend/automations/entity_locator.py
- field_friend/automations/field_provider.py
- field_friend/automations/implements/implement.py
- field_friend/automations/implements/tornado.py
- field_friend/automations/implements/weeding_implement.py
- field_friend/automations/implements/weeding_screw.py
- field_friend/automations/kpi_provider.py
- field_friend/automations/navigation/crossglide_demo_navigation.py
- field_friend/automations/navigation/field_navigation.py
- field_friend/automations/navigation/follow_crops_navigation.py
- field_friend/automations/navigation/navigation.py
- field_friend/automations/navigation/straight_line_navigation.py
- field_friend/automations/path_provider.py
- field_friend/automations/plant_locator.py
- field_friend/automations/plant_provider.py
- field_friend/interface/components/log_monitor.py
- field_friend/interface/components/status_drawer.py
- field_friend/interface/dev_page.py
- field_friend/interface/low_bandwidth_page.py
- field_friend/robot_locator.py
- field_friend/system.py
- field_friend/vision/calibratable_usb_camera_provider.py
- field_friend/vision/zedxmini_camera/zedxmini_camera_provider.py
- main.py
- requirements.txt
- tests/conftest.py
- tests/test_field_provider.py
Adapt to changes made to the RoSys persistence system in https://github.com/zauberzeug/rosys/pull/266
ToDos:
> Update RoSys to 0.24.1 and implement new persistence system

- config/u6.py
- requirements.txt
@Johannes-Thiel After your hardware fix the robot's driving directions were switched. So I switched the configuration.
> Switch motor directions for U6

- field_friend/automations/navigation/field_navigation.py
The robot will not always dock to the charging station on the first try. With this it will try again and add small lateral offsets to adjust for positional errors.
> Retry to dock to the charging station on failure
