Dockerfile
For handling geodata and implement a file-upload for shape and KML files, geopandas and GDAL is needed. Also GDAL now enables a wide possibility of processing geodata for future works
=> adding gdal and geopandas installation to Dockerfile

field_friend/interface/geodata_picker.py
Due to the fact that shape-files are made up of several files (minimum: .shp, .shx and .dbf) The shape-files needs to be compressed into a zip-folder. Uploading this folder works fine for extracting the shape's information.
=> shape file upload as zip file

field_friend/automations/field_provider.py, field_friend/interface/field_planner.py
1. Possibly, all points of a field could be deleted by the user. When a new point is then added to the empty list, this point will be the new reference point of the field. We want to prevent the system from doing this because the field's rows and its crops are depending on this reference point. 
2. the reference of the field can now be accessed by symply requesting `field.reference`. This will return the reference lat and lon as a list, e.g. `[52.0000,7.0000]`.
=> Set Field Reference only when it is None

field_friend/navigation/gnss.py
Somehow wrapping pynmea2.parse in  run.cpu_bound produced random rosys shutdowns. While the underlying core issue is still not understood, removing the cpu_bound wrapping makes the random shutdowns disappear.
=> Fix random shutdowns produced by GNSS signal data

field_friend/interface/components/automation_controls.py
This PR correctly awaits the `can_start` handler passed to the automation controls.
=> Correctly await `can_start` handler in automation controls

field_friend/interface/components/leaflet_map.py, field_friend/interface/pages/field_planner_page.py, field_friend/interface/pages/main_page.py
This PR introduces a button bar for the leaflet map to center on the robot and toggle between basemap (satellite | openstreetmap):
=> Provide map buttons to center on robot and toggle basemap

field_friend/interface/components/key_controls.py
This PR removes the keyboard shortcut to restart the system. In the current form it does not work (because SHIFT always leads to an capital `R`) and in general this should be not be triggered by accident.
=> Remove non-functional restart via keyboard shortcut

field_friend/interface/components/operation.py, field_friend/system.py
This PR fixes persistence by using RoSys instead of a per-user storage (which then may change the currently selected automation in the system).
=> Persist current automation via RoSys, not app.user

docker-compose.yml, field_friend/system.py, main.py
This pull request reads the ROBOT_ID from the .env file instead of the hard coded variable it was before. Normally the ROBOT_ID should be really the robot (eg. F13, U6, ...) and not the Robot Brain serial number. Because config parsing currently is based on that, a VERSION can also be defined which is then used by System.
NOTE: This branch is based on https://github.com/zauberzeug/field_friend/pull/75.
=> Use .env to specify robot id / version

field_friend/hardware/double_wheels.py
This is a fix for Issue #81 . The core_message_field generation had a bug, where a set was added to a list. Now the list is extended  if the Odrive version is 0.5.6.
=> fix core_message_field generation for double_wheels

field_friend/automations/implements/tornado.py, field_friend/automations/implements/weeding_screw.py, field_friend/automations/plant_provider.py, tests/test_plant_provider.py
The crop position prediction doesn't help on fields with unstructured/irregular crop positions. And probably is even detrimental to the crop positioning.
This PR just provides a checkbox to disable it.
ToDos
=> Add checkbox to disable spacing-related crop prediction

field_friend/interface/components/field_object.py, field_friend/interface/components/field_planner.py, field_friend/interface/components/header_bar.py, field_friend/interface/components/leaflet_map.py, field_friend/interface/components/operation.py
This PR fixes #89 with it's first commit.
The second commit switches all other ui related registers to register_ui.
=> Switch ui events from register to register_ui

.syncignore, field_friend/automations/implements/weeding_implement.py
As described in #94 the weeding implement moves down when the automation is stopped.
We identified the [line](https://github.com/zauberzeug/field_friend/blob/140304cdbbbffb0ec8966a649316c890f60f3073/field_friend/automations/implements/weeding_implement.py#L75)
=> fix: Weeding Screw moves down when automation is stopped

field_friend/interface/components/plant_object.py
This pull request makes the plant objects in 3d only appear if the configured thresholds in the Plant Provider are met. To see all plants (and not just the ones around the robot) a `max_distance` of 1000 m is chosen for now.
This will help us to debug #100.
=> Only draw plants in 3d if they are above the threshold

field_friend/automations/plant_locator.py
As requested by @denniswittich this PR adds 'autoupload' to the tags send to the detector.
This was tested on U4/RB28.
=> Add 'autoupload' to detector tags

field_friend/log_configuration.py
Lately RoSys introduced more debug logging for the Axis camera system. Because it pollutes the whole Field Friend log, I suggest we disable debug logs for RoSys.
**ToDos**
=> Do not show rosys debug logs

docker-compose.jetson.orin.yml, field_friend/automations/plant_locator.py
A REST api to pause the upload of images to the learning loop was added to the detector node.
This PR adds a checkbox to call that api, but it still needs some work.
In the future we want it to automaticly upload when a wifi connection is detected and deactivate it when using a mobile connection.
=> Deactivate image upload of detector

field_friend/automations/plant_locator.py
Since this log comes up every second, it should be set to debug.
It is already tested on U6/RB34.
=> Change set_outbox_mode log to debug

.github/workflows/test.yml, field_friend/__init__.py, tests/test_gnss.py, tests/test_navigation.py
This pull request fixes some tests and ensures the tests are all executed on every push. This will help to quickly identify regressions.
=> Run tests as continuous integration with GitHub Action

field_friend/automations/implements/implement.py, field_friend/automations/implements/punch_dialog.py, field_friend/automations/implements/tornado.py, field_friend/automations/implements/weeding_implement.py, field_friend/automations/implements/weeding_screw.py, field_friend/automations/navigation/navigation.py, field_friend/automations/puncher.py, field_friend/interface/components/operation.py
This pull request moves the punch dialog into weeding implements to simplify architecture. The `get_stretch` is the only place where the plant_id is ready available so it makes sense to ask the user there.
=> Fix punch dialog for the refactorings which have been done on #102

.github/workflows/milestone_check.yml
We added an action to Rosys that checks whether a milestone is set for a PR or not ([Link](https://github.com/zauberzeug/rosys/pull/143)). This PR adds the same
=> Add milestone_check action 

field_friend/vision/simulated_cam_provider.py
RoSys introduced a new abstract method in the CameraProvider (see https://github.com/zauberzeug/rosys/pull/139). This PR adds it to our own.
=> Fix compatibility with latest rosys

field_friend/automations/field.py, field_friend/automations/field_provider.py, field_friend/automations/navigation/coverage_navigation.py, field_friend/automations/navigation/row_on_field_navigation.py, field_friend/automations/path_provider.py, field_friend/automations/path_recorder.py, field_friend/interface/components/field_creator.py, field_friend/interface/components/field_object.py, field_friend/interface/components/field_planner.py, field_friend/interface/components/leaflet_map.py, field_friend/interface/components/status_dev.py, field_friend/interface/components/status_drawer.py, field_friend/localization/__init__.py, field_friend/localization/geo_point.py, field_friend/localization/gnss.py, field_friend/localization/gnss_simulation.py, field_friend/system.py, tests/conftest.py, tests/test_field_creator.py, tests/test_field_provider.py, tests/test_gnss.py, tests/test_navigation.py
This pull request simplifies the handling of coordinates by replacing the per-field geo reference a global reference which is set once and never changes. This simplifies the code a lot and is less error-prone.
The reference can be changed by the press of a button in the Field Planner. It takes the current position of the robot as new reference and restarts the system (because all cartesian coordinates floating in memory needs to be recalculated according to the new reference point).
**ToDos**
=> Remove individual field references in favour of a simplified "global" reference for all coordinates

field_friend.code-workspace
We do not develop NiceGUI while working with the Field Friend.
=> Remove nicegui from vscode workspace

field_friend/system.py
In the next RoSys release, icecream is not installed anymore by default. This PR makes icecream available in the Field Friend code again.
=> Add support for icecream

field_friend/automations/automation_watcher.py, field_friend/automations/field_provider.py, field_friend/interface/components/field_creator.py, field_friend/localization/gnss.py, field_friend/localization/gnss_simulation.py, tests/test_gnss.py
The GNSS module sends information formatted along the NMEA-0183 standard. We are currently using the Lat/Lon position from the [GNS message](https://receiverhelp.trimble.com/alloy-gnss/en-us/NMEA-0183messages_GNS.html) which contains GNSS data. For data quality checks we are further using the gps_qual of the [GGA massage](https://receiverhelp.trimble.com/alloy-gnss/en-us/NMEA-0183messages_GGA.html) which only refers to GPS. The mode_indicator of the GNS message contains the mode of every single satellite system. 
Todo:
=> Mode_indicator of GNS instead of the gps_qual from GGA sentence

field_friend/hardware/chain_axis.py, field_friend/hardware/tornado.py
Remove unnecessary ; in the lizard startup. Without these the Fieldfriend can be configured.
This issue is decribed in https://github.com/zauberzeug/lizard/issues/59
=> hotfix for lizard issue #59

field_friend/automations/navigation/follow_crops_navigation.py, field_friend/automations/navigation/navigation.py, field_friend/automations/navigation/row_on_field_navigation.py, field_friend/automations/navigation/straight_line_navigation.py, tests/test_navigation.py
Before, follow crops stopped when no crops were detected. Now follow crops extends straight line and continues to drive the remaining distance in a straight line from the last crop pose.
ToDo:
The tests for `RowsOnFieldNavigation` work for now, but I didnt check them further
=> Follow Crops: drive straight without crops

config/ff13_config_rb36/params.py, field_friend/automations/puncher.py
Changes were tested on F13 and discussed with @rodja and @angelom93. I will merge it right away
=> F13 work_x and demo height adjustment

field_friend/automations/plant_locator.py
Due to latest changes in PR #140 we now automatically change the upload status and do not need the checkbox for (de)activating it anymore.
=> Delete Image Upload Checkbox

field_friend/hardware/axis_D1.py, field_friend/hardware/safety.py
Make the fix discussed in https://github.com/zauberzeug/lizard/issues/66.
Fix a bug in the d1 axis, where the wrong compute steps functoin was used.
=> Fix for lizard issue 66

config/f15_config_f15/robotbrain.py, field_friend/hardware/field_friend_hardware.py
on f15 enable on startup does not work. This is a work around.
=> make a enable on startup param

field_friend/interface/components/camera_card.py, field_friend/interface/components/plant_object.py
During simulation two errors arrows where a Point was used instead of a Point3d. This is connected to #169
=> Fixing Point3d in camera_card and plant_object

requirements.txt
Rosys 0.16.1 is now released!
Release notes:
[0.16.0](https://github.com/zauberzeug/rosys/releases/tag/v0.16.0)
[0.16.1](https://github.com/zauberzeug/rosys/releases/tag/v0.16.1)
=> Update to rosys 0.16.1

field_friend/vision/calibratable_usb_camera.py
While setting up the persistence for https://github.com/zauberzeug/field_friend/pull/168, I noticed that the `to_dict` function does too much, because the parent classes already do that.
=> Refactor to_dict of CalibratableUsbCamera

docker-compose.jetson.orin.yml, field_friend/automations/implements/weeding_implement.py, field_friend/automations/implements/weeding_screw.py, field_friend/automations/plant_locator.py, field_friend/interface/components/plant_object.py, field_friend/interface/components/robot_scene.py, field_friend/system.py, tests/test_weeding.py
We will move the plant detection to a new learning loop project. These are the needed changes on the field_friend side
=> Move to new learning loop project and update detector

field_friend/automations/navigation/navigation.py, tests/test_navigation.py
We had driving timeouts when starting an automation the first time, because the target position was set before the robot updated it's position. This PR fixes that.
=> Fix gnss navigation bug 

field_friend/automations/field_provider.py
Hello,
in the FieldProvider class, there are multiple instances of mutable default arguments.
I have observed, that when using the FieldFriend and creating a field, adding more than one row results in the rows sharing the same points until restarted.
The root cause are mutable default arguments (the list of points given when calling create_row as example), which are then referenced in 2 different instances of Row. When restarting the the program, the rows are restored from a file, in which case, the list of points are instantiated seperately (fixing this shared reference).
The fix is to simply change the function to explicitly create a new list, when no argument is supplied.
=> field_provider.py mutable default argument

field_friend/localization/gnss_simulation.py, tests/test_navigation.py
The GNSS simulation is currently not updating the heading, which it should with our RTK system.
`test_follow_crops_with_slippage` failed., because the heading that was expected before was based on wrong behaviour.
=> Use GNSS RTK in simulation 

requirements.txt
[v0.17.0](https://github.com/zauberzeug/rosys/releases/tag/v0.17.0)
[v0.17.1](https://github.com/zauberzeug/rosys/releases/tag/v0.17.1)
=> Update Rosys to v0.17.1

field_friend/automations/navigation/field_navigation.py
While testing the Field Navigation we observed small GNSS connection losses that led to Driving Timeoutes, why the automation should stop when GNSS signal is lost
=> Field Navigation GNSS Fix

field_friend/automations/navigation/field_navigation.py
Before the robot was turning in fixed steps without adjusting the steps in between.
This PR solves this, but we have to test if the robot wiggles around the target heading when it overshoots just a little.
=> Rework turning after row

field_friend/automations/navigation/field_navigation.py
It is not needed for the field navigation with plants and could be the cause for an automation freezing issue
=> Deactivate GNSS watcher in field navigation

field_friend/automations/field.py, field_friend/automations/field_provider.py, field_friend/automations/navigation/field_navigation.py, field_friend/interface/components/field_creator.py, field_friend/interface/components/leaflet_map.py, field_friend/interface/components/operation.py, field_friend/interface/components/support_point_dialog.py, tests/conftest.py, tests/old_field_provider_persistence.json, tests/test_field_creator.py, tests/test_field_provider.py, tests/test_navigation.py
After creating a simple field with row number, row spacing and buffer width this PR now adds the possibility to specify beds. By simple indicating the number of beds and the spacing between those, a field can how have beds. The row number will then be the number of rows per bed. Safety points still work as before and the calculation of the further rows are based on those.
Todo:
=> Field with Beds

field_friend/localization/gnss.py
We couldn't drive indoors, because the distance to reference check was failing without a valid gnss position
=> Allow navigation without GNSS

field_friend/automations/field_provider.py, field_friend/interface/components/operation.py, field_friend/interface/components/status_dev.py, tests/test_navigation.py
It wasn't possible to start an automation without selecting beds, now it just takes all rows as intended.
Additionally, the odometry info on the dev page is fixed
=> Fix bed selection

tests/test_navigation.py
In PR #221 we implemented the functionality to start the field navigation from anywhere on the field and inside its safety boundary. 
This PR adds test for this functionality
=> Tests for Continue Field Navigation

field_friend/automations/plant_locator.py
When doing tests in the field, we noticed, that the watchdog is not relevant to the enduser. For this reason we are changing the notifications to a debug log.
=> change detector watchdog to debug log

field_friend/interface/components/operation.py, field_friend/system.py
When something fails during startup of `System`, other background tasks are already started and try to access variables of System, like here: `AttributeError: 'System' object has no attribute '_current_navigation'`
The problem is, these tasks will continue running and will fill up the log, which makes finding the error difficult.
The following log is just right after startup, while exception of the original error is just the first one, like here https://github.com/zauberzeug/field_friend/issues/264.
As a note:
We should rework how the current navigation and impement are served, but that is beyond the scope of this PR.
<details>
<summary>Error Message</summary>
```
rosys_1       | 2025-01-23 21:57:39.847 [INFO] rosys/hardware/gnss.py:206: Found GNSS device: /dev/ttyACM1
rosys_1       | …
```
=> Set default system variable values

requirements.txt
Fixes https://github.com/zauberzeug/field_friend/issues/264
=> Update to RoSys 0.22.1 to fix GNSS error #264

field_friend/automations/field.py
I found a bug in backing up fields. At one point returning the bed_crops as part of the field is missing which leads to not making a backup with those bed_crops.
=> Fixing missing bed_crops backup bug

field_friend/automations/navigation/field_navigation.py, field_friend/automations/navigation/navigation.py
We mostly use straight line indoors without a sufficient gnss signal, so the navigation fails.
This PR just warns the user when using a normal navigation without valid gnss. When running the field navigation it fails, because we definitely need it there.
=> Move GNSS distance to reference check to field navigation

field_friend/hardware/field_friend.py, field_friend/hardware/field_friend_hardware.py, field_friend/hardware/field_friend_simulation.py
When looking into the calculation for m_per_tick, we noticed, that the pi is canceld out. 
$` \frac{TC*P*\pi }{\pi*MGR}=\frac{TC*P}{MGR} `$
This will make the formula easier to understand and calculate. It also removes two imports.
=> Remove unnecessary Pi in m_per_tick

field_friend/interface/components/field_object.py
Debuging the field navigation can quite hard with a lot of rows, so this PR displays the row id next to the row in the 3d scene.
=> Display row ids in 3d scene

field_friend/hardware/field_friend.py, field_friend/interface/components/camera_card.py
All tools are at least slightly off the center of the robot and that has to be taken in account when weeding.
Before, the work offsets were added in the puncher, but not in the `can_reach` function, which led to errors when the robot drove to a weed that it in the end couldn't reach.
=> Use tool offset in can_reach

odrive/calibrate_two_motors_l.py, odrive/calibrate_two_motors_r.py
This will limit the maximum continous draw of the odrives to 20 A
=> Lower odrive max current

field_friend/api/fields.py, field_friend/automations/field.py, field_friend/automations/field_provider.py, field_friend/interface/components/field_creator.py, field_friend/interface/components/operation.py, field_friend/interface/components/support_point_dialog.py, tests/conftest.py, tests/test_field_creator.py, tests/test_field_provider.py, tests/test_navigation.py
Currently we handle beds and rows for users with a name starting at 1. For a cleaner code we would not just the internal indexes starting at 0 but also the row and bed numbers.
=> Start bed and row indices at 0

.github/workflows/test.yml
Before, if one check failed, all had to be rerun. This PR solves this.
@codingpaula is there an advantage of checking ruff alone and not as part of pre-commit?
=> Split up code checker jobs to run them separately

field_friend/automations/field_provider.py, field_friend/automations/path_provider.py, field_friend/automations/plant_provider.py, field_friend/hardware/teltonika_router.py, field_friend/interface/components/header_bar.py, field_friend/interface/components/log_monitor.py, field_friend/system.py, requirements.txt
Update to [RoSys 0.23.0](https://github.com/zauberzeug/rosys/releases/tag/v0.23.0) which includes features that were already needed on main.
https://github.com/zauberzeug/rosys/pull/264 introduced typed events as part of 0.23.0, some events had to be annotated because of it.
Was tested on U4
=> Update to RoSys 0.23.0

field_friend/system.py
Before only the geo position of the `GeoReference` was saved in the persistence.
Now the heading is also saved and I added a check that handles old persistence data.
=> Save GeoReference heading in persistence

field_friend/api/automation.py, field_friend/api/status.py, field_friend/automations/automation_watcher.py, field_friend/automations/implements/weeding_implement.py, field_friend/automations/navigation/field_navigation.py, field_friend/automations/navigation/navigation.py, field_friend/automations/plant_locator.py, field_friend/interface/components/field_creator.py, field_friend/interface/components/leaflet_map.py, field_friend/interface/components/support_point_dialog.py, field_friend/interface/dev_page.py, field_friend/robot_locator.py, field_friend/system.py
This PR solves three issues and adds some convenient logging:
1. The `RobotLocator` would fail if `gnss` was None, this PR only registers to `Gnss.NEW_MEASUREMENT` if `gnss` is present. A lot of checks all around the codebase were necessary
2. Setting the standard deviations to zero leads to numerical instabilities in the covariance matrix, so 1e-10 is used
3. The `_ignore_gnss` and `_ignore_imu` are now set to `True` if the sensor is `None`
Was tested on U4
=> Make gnss optional and avoid numerical instabilities in simulation

field_friend/interface/__init__.py, field_friend/interface/components/header_bar.py, field_friend/interface/low_bandwidth_page.py, field_friend/interface/main_page.py, main.py
When checking our cameras, we noticed that the main page uses up to 250 MB of data per hour. To reduce this, we removed the camera, the Leaflet map, and the robot scene. To still have some idea of what the robot is doing, we are adding the log view and state tracking to this page
=> Add low bandwidth page

field_friend/automations/implements/tornado.py, field_friend/automations/implements/weeding_implement.py, field_friend/interface/components/camera_card.py
The overlay was quite overwhelming and not always helpful when looking for errors.
What I did:
1. Add lines that mark the limits of the work area
2. Make all overlays thinner
3. Change show_weeds_to_handle to show_plants_to_handle to allow for a crop overlay 
4. Change some logs
Before:
Now:
With Tornado overlay:
=> Improve debugging visibility with a lighter image overlay

field_friend/robot_locator.py
After startup and after resetting the Kalman Filter, the robot did not update it's position and only after driving for some time, it eventually did catch its correct position.
This change now forces an update to find the correct starting position.
=> Reset the robot's position to the gnss position on startup and reset

field_friend/config/configuration.py, field_friend/hardware/tornado.py
<details>
<summary>ref_knife_ground_inverted tests</summary>
With U4, F12 and F13 I did the same test to check whether the knife end stop is inverted or not, which shows that they should not be inverted.
In the air: 
```
> tornado_ref_knife_ground.inverted
true
> tornado_ref_knife_ground.level
0
> tornado_ref_knife_ground.active
true
```
On the ground:
```
> tornado_ref_knife_ground.level
1
> tornado_ref_knife_ground.active
false
```
</details>
<details>
<summary>Active property</summary>
`ref_motor_inverted` is `True`, so
```
ref_motor.level == 0
```
becomes
```
ref_motor.active == true
```
-------
`ref_gear_inverted` is `False`, so
```
ref_gear.level == 1
```
becomes
```
ref_motor.active == true
```
Same for `ref_knife_ground` and `ref_knife_stop`
</details>
=> Make tornado end stop inversion configurable and use the active property instead of level

field_friend/hardware/safety.py
The tornado safety was forgotten in https://github.com/zauberzeug/field_friend/pull/321 which stops both the wheels and the y axis when the tornado blade is in the air.
I will merge this without review, because it's so small and I tested it directly on U4
=> Adapt tornado safety to knife_ground sensor inversion

field_friend/interface/components/field_creator.py
To avoid users having to re-record points if the Field Creator is cancelled, it is now possible to load points from storage. If a point is recorded but no field has been saved yet, it can be used to create the field.
=> Save field creator points in app storage

config/u4.py, config/u6.py, field_friend/config/configuration.py, field_friend/hardware/field_friend_hardware.py, requirements.txt
Implements https://github.com/zauberzeug/rosys/pull/292
We can now optionale use Lizard's espresso.py and check whether the ESP is connected or not.
@Johannes-Thiel and I already talked about this and I will merge this without review.
=> Implement `RobotBrain` changes from RoSys #292

config/u6.py
I flashed the Odrives of u6 with the version of `0.5.6`. To reflect this we need to change the version in the config.
=> Update ODrive version for U6 to 0.5.6

config/u5.py, config/u6.py, field_friend/hardware/y_axis_canopen_hardware.py, field_friend/hardware/z_axis_canopen_hardware.py
**Motivation**
When doing testing on the Canopen axis of `u5` we noticed, that the `z_axis` will sometimes not move upwards after it has drilled. When we did some further investigation we also saw, that sometimes the referncing will not work, when the robot has just started up. This happend without any feedback, as to why it did not work.
**Implementation**
To combat these errors we made the axis more robust with the usage of asserts and handling the static wait times in while loops. The while loops were chosen, in order to make shure that all the nececarry steps are taken in the right order, with dynamic wait times. We are now checking, if the `robot_brain.is_ready`, the motor is `initalized` and if the motor `is_operational`. These checks are made to ensure, that the hardware is ready …
=> Make the Canopen axis more robust

field_friend/automations/navigation/field_navigation.py, field_friend/automations/navigation/navigation.py, field_friend/system.py, requirements.txt
When using the normal rosys garbage collection all functions will be stopped each minute. To prevent this we are calling the garbage collection manually, before enabling the implement when starting a new row and after the automation is finished. If no atomation is running we are starting the garbage collection every 5 minutes.
We choose to use the garbage collection in the `field_navigation.py` at this point, because the robot is standing still while the implement will be enabled. For this reason a second of additional waiting time is okay.
edit: the commit message "update to RoSys 0.25.1" is not correct, it is an update to 0.25.0
=> Manually use garbage collection

field_friend/automations/plant_locator.py, main.py
The Learning Loop saves a source for every image. We currently do not use that feature, which is helpful to filter all images by the source.
Just adds the `source`-argument to `Detector.detect`.
I also made sure that `robot_id` is always lowercase.
=> Set the robot's id as detector source

field_friend/interface/components/field_object.py
In https://github.com/zauberzeug/field_friend/pull/343 I introduced labels for the bed indices in the 3D scene. I forgot to remove them, when the field is deselected.
Check for all objects beginning with 'bed_', the same as for rows and fields.
=> Fix bed name removal from `FieldObject`

field_friend/automations/navigation/field_navigation.py, field_friend/automations/navigation/straight_line_navigation.py, tests/test_field_provider.py, tests/test_navigation.py
Locally executed navigation tests produce two failures:
```
FAILED tests/test_navigation.py::test_straight_line_with_high_angles - TimeoutError: condition took more than 100 s
FAILED tests/test_navigation.py::test_driving_to_exact_positions - TimeoutError: condition took more than 100 s
```
I fixed some formatting, added a epsilon to the StraightLineNavigation "should_stop" and switched back to normal driving speed for the exact positions test.
=> Formatting and cosmetical changes for the navigation code

main.py
I accidentally had set the `ROBOT_ID` in my environment and wondered why my changes to `.env` where not applied.
`load_dotenv` has a `override` parameter, that ignores values from the current environment.
=> Ensure environment variables are loaded from the .env file

.cursor/rules/coding.mdc, .cursor/rules/general.mdc, CONTRIBUTING.md
Provide rules for [Cursor IDE](cursor.com) and a CONTRIBUTION.md file for humans.
Main instructions are in the markdown file and .cursor/rules only adds specific AI instructions plus a reference to the markdown
=> Add basic set of cursor rules

config/f20.py, field_friend/system.py, requirements.txt, tests/conftest.py, tests/test_navigation.py
The upcoming [RoSys release](https://github.com/zauberzeug/rosys/releases/tag/v0.26.0) will have some helpful additions and fixes.
1. https://github.com/zauberzeug/rosys/pull/302
2. https://github.com/zauberzeug/rosys/pull/303
- I set `throttle_at_end_min_speed` to 0.05
- As expected with a minimum speed, deceleration distances will change. That's why I adjusted tolerances in the tests.
- I set `use_acceleration` to `False` by default, because we have tests for it and it's annoying in simulation
4. https://github.com/zauberzeug/rosys/pull/304
5. https://github.com/zauberzeug/rosys/pull/306
- I removed the workaround for the test fixtures
6. I added and tested the F20 config, which is only for testing because it belongs to another project
=> Update RoSys, implement the driver's minimum speed limit and remove persistence workaround

field_friend/automations/implements/tornado.py, field_friend/automations/puncher.py, field_friend/hardware/tornado.py, tests/test_weeding.py
This PR implements multiple improvements developed by @SeaTechRC to make the Tornado implement faster and less harmful for the crops.
- Decrease waiting times between move commands
- Skip of crops when no weeds are in the vicinity
- Variable drill depth to avoid damage to the roots of the crops when the soil is too loose
- Add a more intuitive slider for the tornado angle
- Calculate a corrected tornado angle: When turning to its angle, at the start already turn away from the plant to not harm them afterwards when returning to 0°
- 0° is still 0°
- 180° is still 180°
- 90° becomes 270°
- 170° becomes 190°
- Minor cleanups
=> Improve Tornado weeding workflow

.syncignore, docker-compose.jetson.orin.yml, docker-compose.jetson.yml, field_friend/interface/components/monitoring.py, field_friend/system.py
We switched to a new learning loop project, specialized for the fieldfriend circle sight.
It's not exactly a breaking change, like the tag suggests, but it can lead to orphan containers since the service was renamed.
- Switch to new project
- Update old compose file to fieldfriend plant project
- Small cleanups
How to:
1. Stop and remove monitoring container
2. Rename `~/data_monitoring` directory to `~/data_circlesight`
3. `./docker.sh U`
=> Switch monitoring to new CircleSight project

field_friend/app_controls.py, field_friend/automations/navigation/__init__.py, field_friend/automations/navigation/field_navigation.py, field_friend/automations/navigation/waypoint_navigation.py, field_friend/interface/dev_page.py, field_friend/robot_locator.py, field_friend/system.py, pyproject.toml, requirements.txt
This PR updates to [RoSys 0.28.0](https://github.com/zauberzeug/rosys/releases/tag/v0.28.0) and does some minor changes to make this library easier to handle for other projects.
- Update RoSys and allow python versions 3.11, 3.12 and 3.13
- Make `is_reference_valid` and `RobotLocator.reset` public
- Add the `GNSS_REFERENCE_CHANGED` event to `System`
- Raise `GnssHardware.MAX_TIMESTAMP_DIFF` to 0.25 seconds
- Minor cleanups to make it usable for other non field friend hardware
=> Update to RoSys 0.28.0

.gitignore, .syncignore, config/f12.py, config/f13.py, config/f14.py, config/f15.py, config/f19.py, config/f20.py, config/f21.py, config/f22.py, config/u4.py, config/u5.py, config/u6.py, docs/tutorials/imu_calibration.md, docs/tutorials/tutorials.md, field_friend/config/configuration.py, field_friend/robot_locator.py, field_friend/system.py, requirements.txt, tests/conftest.py, tests/test_gnss.py
Since our GNSS antennas are on the top of the robot, the position will be wrong when the robot is tilted.
@Johannes-Thiel already started to implement this in https://github.com/zauberzeug/field_friend/pull/232 (with a useful diagram), but I think this implementation is more sleek.
⚠️ Breaking change: Due to a misunderstanding the IMU configuration of other robots are probably wrong. So I will remove all configurations and add documentation on how to configure it.
=> Correct GNSS position with roll and pitch

field_friend/api/status.py
The lizard versions can't be read from the ESP when it is not ready yet. This PR handles the `EspNotReadyException`.
=> Fix status API when ESP is not ready

field_friend/automations/implements/recorder.py, field_friend/automations/navigation/field_navigation.py, field_friend/automations/navigation/waypoint_navigation.py, field_friend/automations/plant_locator.py, field_friend/interface/components/robot_scene.py, field_friend/system.py
The Recorder implement will record a lot of images that are not really needed for the first trainings. That is why you can now set the recording interval in the implement settings menu.
=> Limit the Recorder's capture interval

field_friend/interface/components/leaflet_map.py
The LeafletMap was using the GNSS measurement position directly, which caused a jumpy icon position but more importantly made it hard to detect problems with the Kalman Filter or the GNSS reference.
I also reduced the map update interval to a 5 second timer. Because the GNSS event comes in every 0.1 seconds, which is not necessary.
=> Use RobotLocator's position on LeafletMap

field_friend/hardware/double_wheels.py, requirements.txt
We had Issue where the ODrive motor controllers delivered a far too high velocity reading.
https://github.com/zauberzeug/lizard/pull/160
This PR adds a safeguard to skip those measurements.
=> Check velocity readings for validity
